# commments are written using #
# name field is not necessary
# if not provided, github displays the whole path name - .github/workflows/main.yml in this case
name: first github action test learning

on:
  workflow_dispatch:

# job is needed to be provided otherwise the build would show failed with message - No jobs defined in `jobs`
jobs:
  # below is a key for job (if it was json)
  # a job requires either runs-on or uses
  deploy:
    runs-on: ubuntu-latest
    # No steps defined in `steps` and no workflow called in `uses` for the following jobs: deploy
    steps:
      - name: First Step - before checking out
        env :
          TEST_ENV: "test"
        # below is a single line command
        run: echo "hi"
      
        # with cannot be used with run, but rather should be used with uses
        # with:
          # first: "hello"
        # below is a multi line command
        # for multi line commands, you cannot add comments in between
        # the readme command should fail as we have not checked the repo yet, indeed it does with below error
        # cat: README.md: No such file or directory
        # run: |
          # echo "hello ${TEST_ENV}"
          # echo "$(ls -la)"
          # cat README.md
      - name: temporary step - ignore
        run: |
          echo $GITHUB_WORKSPACE
          echo $(pwd)
          echo $(ls -a)
      - name: Second Step - checking out
        # so run cannot be used with uses
        # run: echo "hi"
        uses: actions/checkout@v4
        with:
          # let us see what happens when we provide the path field to it
          path: "testing-path"
      - name: Third Step - after checking out
        run: |
          echo $(pwd)
          echo $(ls -a)
    

