# commments are written using #
# name field is not necessary
# if not provided, github displays the whole path name - .github/workflows/main.yml in this case
name: first github action test learning

on:
  workflow_dispatch:

# job is needed to be provided otherwise the build would show failed with message - No jobs defined in `jobs`
jobs:
  # below is a key for job (if it was json)
  # a job requires either runs-on or uses
  deploy:
    runs-on: ubuntu-latest
    # No steps defined in `steps` and no workflow called in `uses` for the following jobs: deploy
    steps:
      - name: First Step
        env :
          TEST_ENV: "test"
        # below is a single line command
        # run: echo "hi"
        
        # below is a multi line command
        # for multi line commands, you cannot add comments in between
        # the readme command should fail as we have not checked the repo yet
        run: |
          echo "hello ${TEST_ENV}"
          echo "$(ls -la)"
          cat README.md
    # uses: actions/checkout@v2
    

